<!doctype html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>EatMukka.com</title>
	<meta name="theme-color" content="#317EFB" />
	<link rel="stylesheet" href="/vendor/bootstrap-5.1.3-dist/css/bootstrap.min.css" media="print" onload="this.media='all'">
	<link rel="stylesheet" href="/css/site.css?v=1.2.9" media="print" onload="this.media='all'">
	<link rel="stylesheet" href="/vendor/bootstrap-icons-1.8.0/bootstrap-icons.css" media="print" onload="this.media='all'">
</head>

<body class="bg-white">

	<?php
	$splashCaption = null;

	$splashImage = '<?xml version="1.0" encoding="utf-8"?>
		<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" style="margin: auto; background: rgb(255, 255, 255); display: block; shape-rendering: auto;" width="200px" height="200px" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid">
		<rect x="19" y="19" width="20" height="20" fill="#e15b64">
		<animate attributeName="fill" values="#f8b26a;#e15b64;#e15b64" keyTimes="0;0.125;1" dur="1s" repeatCount="indefinite" begin="0s" calcMode="discrete"></animate>
		</rect><rect x="40" y="19" width="20" height="20" fill="#e15b64">
		<animate attributeName="fill" values="#f8b26a;#e15b64;#e15b64" keyTimes="0;0.125;1" dur="1s" repeatCount="indefinite" begin="0.125s" calcMode="discrete"></animate>
		</rect><rect x="61" y="19" width="20" height="20" fill="#e15b64">
		<animate attributeName="fill" values="#f8b26a;#e15b64;#e15b64" keyTimes="0;0.125;1" dur="1s" repeatCount="indefinite" begin="0.25s" calcMode="discrete"></animate>
		</rect><rect x="19" y="40" width="20" height="20" fill="#e15b64">
		<animate attributeName="fill" values="#f8b26a;#e15b64;#e15b64" keyTimes="0;0.125;1" dur="1s" repeatCount="indefinite" begin="0.875s" calcMode="discrete"></animate>
		</rect><rect x="61" y="40" width="20" height="20" fill="#e15b64">
		<animate attributeName="fill" values="#f8b26a;#e15b64;#e15b64" keyTimes="0;0.125;1" dur="1s" repeatCount="indefinite" begin="0.375s" calcMode="discrete"></animate>
		</rect><rect x="19" y="61" width="20" height="20" fill="#e15b64">
		<animate attributeName="fill" values="#f8b26a;#e15b64;#e15b64" keyTimes="0;0.125;1" dur="1s" repeatCount="indefinite" begin="0.75s" calcMode="discrete"></animate>
		</rect><rect x="40" y="61" width="20" height="20" fill="#e15b64">
		<animate attributeName="fill" values="#f8b26a;#e15b64;#e15b64" keyTimes="0;0.125;1" dur="1s" repeatCount="indefinite" begin="0.625s" calcMode="discrete"></animate>
		</rect><rect x="61" y="61" width="20" height="20" fill="#e15b64">
		<animate attributeName="fill" values="#f8b26a;#e15b64;#e15b64" keyTimes="0;0.125;1" dur="1s" repeatCount="indefinite" begin="0.5s" calcMode="discrete"></animate>
		</rect>
		<!-- [ldio] generated by https://loading.io/ --></svg>';

	if (isset($splashInfo['svgCode']) && !empty($splashInfo['svgCode'])) {
		$splashImage = $splashInfo['svgCode'];
		$splashCaption = $this->Session->read('Site.caption');
	}
	?>
	<div style="display: flex;
  		justify-content: center;
  		align-items: center;
  		text-align: center;
  		min-height: 100vh;">
		<div>
			<?= $splashImage ?>
			<?= $splashCaption ? '<div style="font-size: 0.85em; color: #fa8072;">' . $splashCaption . '</div>' : '' ?>
		</div>
	</div>

	<script src="/vendor/jquery/jquery-3.6.0.min.js"></script>
	<script src="/vendor/bootstrap-5.1.3-dist/js/bootstrap.min.js" defer></script>
	<script src="/js/site.js?v=1.3.1" defer></script>
	<script src="/js/final.js?v=1.1.3" defer></script>
	<script defer>
		$(document).ready(function() {
			window.location = '/';
		});
	</script>
</body>

</html>